stages:
  - build

image:
  name: b4dfever/packer:dev01
  entrypoint:
    - ""

before_script:
  - export PKR_VAR_vsphere_vcenter_server="${vsphere_vcenter_server}"
  - export PKR_VAR_vsphere_username="${vsphere_username}"
  - export PKR_VAR_vsphere_password="${vsphere_password}"
  - export PKR_VAR_vsphere_datacenter="${vsphere_datacenter}"
  - export PKR_VAR_vsphere_host="${vsphere_host}"
  - export PKR_VAR_vsphere_network="${vsphere_network}"
  - export PKR_VAR_vsphere_datastore="${vsphere_datastore}"
  - export PKR_VAR_iso_url="${iso_url}"
  - export PKR_VAR_iso_checksum="${iso_checksum}"

build:
  stage: build
  script:
    - packer --version
    - packer init .
    - packer validate .
    - packer build -only="vsphere-iso.ubuntu-template" .
