stages:
  - validate
  - build
  - export

image:
  name: b4dfever/packer:dev01
  entrypoint:
    - ""

before_script:
  - export PKR_VAR_vsphere_vcenter_server="${vsphere_vcenter_server}"
  - export PKR_VAR_vsphere_username="${vsphere_username}"
  - export PKR_VAR_vsphere_password="${vsphere_password}"
  - export PKR_VAR_vsphere_datacenter="de01m01"
  - export PKR_VAR_vsphere_host="de01m01esx01.badfever.de"
  - export PKR_VAR_vsphere_network="internal"
  - export PKR_VAR_vsphere_datastore="de01m01esx01-local01"
  - export PKR_VAR_iso_url="${iso_url}"
  - export PKR_VAR_iso_checksum="${iso_checksum}"

validate:
  stage: validate
  script:
    - packer --version
    - packer init .
    - packer validate .
